wizeline/wize-q-remix

app/controllers/questions/modifyPinStatus.js, app/utils/backend/constants.js, app/utils/backend/validators/question.js, app/utils/constants.js, tests/integration/controllers/questions/modifyPinStatus.test.js
It adds the 'modifyPinStatus' controller to pin/unpin a question, if the question update is successful, it returns the updated question with a success message. If there's an error, an object with an error property is returned.
- controllers/questions/modifyPinStatus.js
- tests/integration/controllers/questions/modifyPinStatus.test.js
The integration tests added are passing at the moment.
Closes #8
=> feat(controllers): add modifyPinStatus controller with integration tests

app/components/ListQuestions/ListQuestions.jsx, app/components/Notifications/Notifications.jsx, app/components/QuestionRow/QuestionRow.jsx, app/routes/index.jsx, app/utils/actions.js, tests/integration/controllers/questions/listQuestion.test.js
- Adds action for calling pinning/unpinning questions
- Updates notification component to allow singular errors (error attribute instead of errors)
- Should be a good base for voting action #22 , and a example of how we can have multiple actions in one same page.
- Updates list question integration test that was for some unknown reason failing locally.
1. Go to questions list
2. Pin questions and verify a success message is shown
3. Verify question list is sorted
4. Refresh page and verify quesiton is on top, even with filters applied (that match)
5. Do the same for unpinning this question
Closes #23 …
=> feat(frontend): add pinning/unpinning handler

app/components/CounterButton/CounterButton.Styled.jsx, app/components/CounterButton/CounterButton.jsx, app/components/ListQuestions/ListQuestions.jsx, app/components/QuestionCard/QuestionCard.jsx, app/components/QuestionDetail/QuestionDetail.jsx, app/routes/index.jsx, app/routes/questions/$questionId.jsx, app/utils/actions.js
It adds the ability to like a question both in the question list index page and in the question detail page, debouncing multiple clicks in rapid succession using the useState hook available for Remix.
https://user-images.githubusercontent.com/104774638/196557306-842e27d3-4354-439a-80f7-bdc0c0f96c9b.mov
- app/components/ListQuestions/ListQuestions.jsx
- app/routes/index.jsx
- app/components/QuestionDetail/QuestionDetail.jsx
- app/routes/questions/$questionId.jsx
1. Apply some filtering criteria in the list of questions that has some results
2. Vote one of the filtered questions
3. The search parameters should be kept after submitting the like action
4. Open the details of a question and verify that we can like the question there as well, with a 'not-allowed' cursor when hovering over the …
=> feat(migration): Add like question action handler in the UI

prisma/schema.prisma, tests/integration/controllers/answers/updateAnswer.test.js, tests/integration/controllers/questions/modifyPinStatus.test.js
- Add @updateAt prisma attribute on the updateAt columns 
- Tables:
- Questions
- Comments
- Answers
- prisma/schema.prisma
- tests/integration/controllers/answers/updateAnswer.test.js
- tests/integration/controllers/questions/modifyPinStatus.test.js
1. run the command `nxp prisma db pull`  to update your db according to your schema. 
[Questions]
[Comments]
[Answer]
2. run the test `npm run test:integration`
3. Verify that all tests have passed.
Ticket raised from the following discussion [feat(migration): add comments list controller](https://github.com/wizeline/wize-q-remix/pull/40#pullrequestreview-1148346757)  
Closes #45
=> feat: add @updatedAt prisma attribute to updatedAt columns. 

app/controllers/comments/create.js, app/controllers/comments/delete.js, app/utils/backend/validators/comments.js, app/utils/constants.js, tests/integration/controllers/comments/createComment.test.js, tests/integration/controllers/comments/deleteComment.test.js, tests/integration/controllers/comments/updateComment.test.js
It adds the delete comment controller and adds the userEmail field when creating a comment if said 'userEmail' property is available in the 'user' object inside the payload for creating a new comment. 
- app/controllers/comments/delete.js
- tests/integration/controllers/comments/deleteComment.test.js
- app/controllers/comments/create.js
Tested by the integration tests included.
Closes #43
=> feat(migration): Add delete comment controller with integration tests

app/controllers/comments/approvedBy.js, app/utils/actions.js, app/utils/backend/constants.js, app/utils/backend/objectUtils.js, app/utils/backend/validators/comments.js, tests/integration/controllers/comments/approvedComment.test.js
- Add controller to approve a comment as answer.
- app/controllers/comments/approvedBy.js
- tests/integration/controllers/comments/approvedComment.test.js
Run the test integration. `npm run test:integration`
Closes #59
=> feat: (migration)Add controller to approve a comment as an answer

app/components/QuestionRow/QuestionRow.jsx, app/controllers/questions/modifyPinStatus.js, app/routes/index.jsx, app/utils/backend/validators/question.js, tests/integration/controllers/questions/modifyPinStatus.test.js
- It fixes the bug parameter error message when pinning/unpinning a question in the question list
- It adds the filtering/ordering query parameters after submitting the pin/unpin action
https://user-images.githubusercontent.com/104774638/200457456-75aea4d8-3351-4e93-be93-cd40460e0d2f.mov
- app/routes/index.jsx
- app/components/QuestionRow/QuestionRow.jsx
Pin/unpin a question from the question list having some filtering/ordering parameters selected, the question must be pinned/unpinned correctly without displaying an error message and the query parameters must be kept.
This is to fix the bug when pinning/unpinning a question issue.
(Link to …
=> fix: error when pinning question from the list and retain filtering/ordering query parameters

app/controllers/answers/create.js, app/controllers/answers/nps/create.js, app/controllers/questions/create.js, app/routes/questions/new.jsx, app/utils/backend/slackNotifications.js, infrastructure/terraform/main.tf, infrastructure/terraform/modules/cloud_run/cloud_run.tf, infrastructure/terraform/modules/cloud_run/variables.tf, tests/integration/controllers/answers/createAnswer.test.js, tests/integration/controllers/questions/createQuestion.test.js
- Fixes bug that slackNotifications had when re-implementing
- Changes the url format to match the new question detail URL
- Adds the notification to answer controller and corresponding test
- Adds environment variable to Cloud Run through Terraform
- Go to #wizeq-dev channel to see the latest bot posts, these were sent through the app locally
Testing locally would require having some .env variables in your local with the Slack credentials. If you are interested I can send them to you in private message.
Style, message, everything pretty much is reused from old app. Old links will be handled with #72 
Closes #81
=> feat: add slack notifications

app/routes/index.jsx
- Add support for the old questions links for the details : ` https://questions.wizeline.com/#/?questionId=1440 `
-  /app/routes/index.jsx
1. Checkout for this branch `frontend/add-redict-to-legacy-url-question`
2. Run the project 
3. Login
4. Go to the next old links:
http://localhost:3000/#/?questionId=1   - _redirect to the question detail_
http://localhost:3000/#/?questionId=10  - _redirect to the question detail_
http://localhost:3000/#/?questionId=2 - _redirect to the question detail_ 
http://localhost:3000/#/?questionId=Hola - _stay on the homepage_
5. Replace the questionId with another id in your local environment. and verify can you can acces to the detail
http://localhost:3000/#/?questionId={replace_id}
Closes #72 …
=> fix: redirect from old link question. 

app/components/Atoms/UserImage/UserImage.jsx
- Added fallback image when profile pictures are not loaded succesfully
- app/components/Atoms/UserImage
1. Check if the placeholder image is displayed when the profile img is not loaded
2. Check if the profile img is displayed correctly when it's loaded correctly
3. :tada:
Closes #90
=> feat: added fallback profile image 

tests/integration/controllers/comments/deleteComment.test.js
- Fixes (or attempt to fix) bug described in #82 
- I believe the bug was a concurrency issue with the generateMinMaxDates validation, so I added a mock for this function to validate that the comment is always on deletable range.
Run the tests locally, although it usually happened during Github Actions / PR
- Ran Actions several times in this PR and didn't get the error again, but we should still keep an eye if it happens again and this were just false positives.
Closes #82
=> fix: deleteComment test intermittent error

infrastructure/cloudbuild.yaml, infrastructure/terraform/master.tfvars, infrastructure/terraform/modules/cloud_run/cloud_run.tf
- Some changes to Terraform files for the first produciton release
- Substr is needed in vpc connector since an error occurred with "wizeq-remix-prod-connector" as this excedeed the mas character limit. To not oveerride the existing "wizeq-remix-dev-connector" in develop, substr is used to only truncate when exceeding 25 characters
=> chore(infrastructure): update terraform production vpc config

.github/workflows/release-config.json, .github/workflows/release.yaml
- Adds Github Action trigger to automatically create release notes using latest semantic commits with tags, done in the same way as the https://github.com/wizeline/anubis project.
- Merging and creating first release should Close #94
=> chore: add release changelog github action

app/components/Modals/AssignAnswerModal/AssignAnswerModal.Styled.jsx
This fix will prevent the departments not being displayed as a scroll was added. 
app/components/Modals/AssignAnswerModal/AssignAnswerModal.Styled.jsx
1. As an admin, on the landing page  click on any question displayed
2. Click on the reassign option of the question
3. Click on the select department dropdown 
4. Verify that you are able to scroll thought the options displayed. 
Closes #157
=> fix: added scroll and prevent overflow

app/components/Notifications/Notifications.jsx, app/components/QuestionForm/QuestionForm.jsx, app/controllers/employees/list.js, app/controllers/questions/create.js, app/routes/employees/getByDeparment/$id.js, app/routes/questions/new.jsx, app/styles/CreateQuestion.Styled.jsx, app/utils/backend/validators/question.js, app/utils/constants.js, tests/fixtures/employeeDepartment.json, tests/initTestDb.js, tests/integration/controllers/employees/getEmployeesByDepartment.test.js, tests/integration/controllers/questions/createQuestion.test.js, tests/tearDownDb.js
- Changes anonymous questions creation to change is_public field to false
- Adds validation/constraint on submit button to enforce an assigned employee when anonymous is toggled on
- Modifies redirect rule to go to question detail instead of home only when its an anonymous question
- Changes globalSuccess toast notification to add the question detail url. This toast does not autoclose.But suggestions to make this feedbnack more visible and better is still appreciated
- Refactors listEmployees controller to fix a bug where some empty user entries would cause an error given they do not have the full_name property. Empty/null entries are now skipped.
Going to the new controller changes mostly
1. Go to question creation and toggle anonymous question on
2. Validate that the submit button is …
=> feat: new anonymous question creation logic

app/components/QuestionForm/QuestionForm.jsx, app/routes/questions/new.jsx
- Updates question creation logic client side to send the assigned_employee_id as undefined instead of null when not selecting any. Will fix question creation error introducced in #177.
1. Create both a normal question (without an assigned employee) and an anonymous question with someone assigned. 
2. Verify the question is created succesfully
Problem is Joi validation that takes null objects and asserts it, for these cases undefined is what we need.
Closes #179
=> fix: refactor assigned_employee_id on question creation from null to undefined

app/controllers/questions/publishQuestion.js, tests/integration/controllers/questions/publishQuestion.test.js
- Sends slack notification when publishQuestion controller is called.
- See addition to the controller
1. Add the slack credentials to your .env (DM me on Slack if you want me to share it)
2. Publish a question
3. Verify that a notification is sent to #wizeq-dev
4. ⚠️ REMOVE the credentials from .env to avoid unintended messages sent
Additionally this is tested with the integration tests and will be test-able in develop env
Closes #187
=> feat: send slack notification on question published

app/components/UserControls/UserControls.jsx
- Uncomments navbar option for mobile, probably I commented it during the app Remix transition for testing and missed uncommenting, sorry about this.
Open any page on mobile view
1. Open navbar option
2. Verify you can logout with the navbar button
Closes #148
=> fix: enable mobile navbar logout option

app/config/emails.json, app/config/flags.json, app/controllers/questions/create.js, app/utils/backend/emails/emailConstants.js, app/utils/backend/emails/templates/views/publicQuestionAssigned.hbs, tests/fixtures/departments.json, tests/integration/controllers/questions/createQuestion.test.js
- Refactors createQuestion controller to send slack and email (to department manager) on both anonymous and public questions.
- Adds feature flag to activate/deactivate sending email and slack on question creating through config
- Adds template for questionAssigned for public questions (its basically almost a copy of the anonymous one for now, but we could make it different)
- If you want to test the emails and slacks locally, send me a Slack so I can give you the .env credentials (we should be careful with these though). Otherwise we can test on develop
Closes #203 
Public
Anon
=> feat: send email to created question department manager

app/components/AdminDepartments/AdminDepartments.jsx, app/components/Modals/EditDeparmentModal/EditDepartmentModal.jsx, app/controllers/departments/list.js, app/controllers/departments/update.js, app/controllers/questions/create.js, app/routes/admin.jsx, prisma/migrations/20230428010538_add_alternate_manager/migration.sql, prisma/schema.prisma, tests/integration/controllers/deparments/update.test.js
- adds a new field to save a substitute of a manager. 
- modify the `createQuestion` controller to send an email to the substitute of a manager. 
1. Login as admin
2. Go to the admin option.
3. Go to the departments tab.
4. Select any department and add a manager and a substitute. 
Closes #212
=> feat: add alternate/substitute manager to the deparments

app/config/flags.json, app/controllers/questions/assignQuestion.js, tests/integration/controllers/questions/assignQuestion.test.js
- add a flag to send an email when re-assigned a question 
- Send an email to the new person 
- To test the emails locally, you can send me a slack to share the .env credentials of [Mailtrap](https://mailtrap.io/) or create your own account and use your own credentials.
Closes #210
=> feat: send email when re-assigned a question

app/routes/api/emails/sendManagerReminder.jsx, app/utils/backend/api/validateKey.js, infrastructure/terraform/data.tf, infrastructure/terraform/main.tf, infrastructure/terraform/modules/cloud_run/cloud_run.tf, infrastructure/terraform/modules/cloud_run/variables.tf, infrastructure/terraform/modules/cloud_scheduler/main.tf, infrastructure/terraform/modules/cloud_scheduler/variables.tf
- Adds terraform infrastructure code to add gcp scheduler that will call the new email endpoint
- Changes api http method to a POST and require a environment provided KEY header
*- Emails for assigned employees will be handled in a different PR.
=> feat(infra): add terraform code to create gcp scheduler for api calls

app/utils/backend/slackNotifications.js, infrastructure/terraform/data.tf, infrastructure/terraform/main.tf, infrastructure/terraform/modules/cloud_run/cloud_run.tf, infrastructure/terraform/modules/cloud_run/variables.tf
- adds new webhook to sent Slack notification to a private channel.
- adds terraform variables/configuration for the new .env `SLACK_WEBHOOK_URL_ADMIN` 
If you want to test locally, add the `SLACK_WEBHOOK_URL_ADMIN` to your .env and send me and DM to share with you the credentials. 
Stakelholder wants to have a private channel for admins only and send notifications to this channel. We already have one, where we send email every time a question is created, but they want to keep it as a public channel.
Closes #219
=> feat: new webhook slack notifications

app/config/emails.json, app/controllers/emails/sendManagerReminder.js, tests/integration/controllers/emails/sendReminder.test.js
- Fixes issue where no emails where queued given a race condition. Adds a 5 minute offset to make sure emails are sent after 24 hours.
=> fix: email previous date validation offset

app/utils/backend/emails/emailHandler.js, infrastructure/terraform/data.tf
- Adds try/catch to email handler so errors are output in console instead of causing 500s
- Temporal terraform force to use prod email services. Will revert this change onee it's tested.
=> fix(emails): send email error catch

app/root.jsx
- add the meta robots with nonindex value. 
- app/root.jsx
1. run the app and verify that you can see the meta with the devtools.
https://developers.google.com/search/docs/crawling-indexing/block-indexing?hl=es-419#:~:text=noindex%20is%20a%20rule%20set,noindex%20rule%2C%20such%20as%20Google
Closes #249
=> fix: wizeq is indexed by google 

app/entry.server.jsx
This pull request added missing headers on the server for better security policies
app/entry.server.jsx
1. Access the application
2. Open the network tab
3. Check the page delivered headers
4. Verify the following headers are present: 
- Content Security Policy
- Anti-clickjacking
- HTTP Strict Transport Security
- X-Content-Type-Options : The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'.
- 
Closes #228 
:question:
=> feat: Added missing headers to the server

infrastructure/terraform/data.tf, infrastructure/terraform/main.tf, infrastructure/terraform/variables.tf
- Adds terraform code to create a new sql environment for postgres, for future migration
- Note the GCP secret values are already created
=> chore(database): add initial test develop database using postgres

prisma/migrations/20230911154259_drop_tables_tags_questiontags/migration.sql, prisma/migrations/20230911181720_add_table_commenttags/migration.sql, prisma/migrations/20230911182810_alter_table_comments_adds_tags_fields/migration.sql, prisma/migrations/20230911211718_alter_table_comments_change_datatype_taggedby/migration.sql, prisma/schema.prisma
- Remove the unnecessary `tags` and `questiontags`
- Add the migration files to add the new table `commenttags` and the relation with `comments` and  `users`, adding the fields `taggedby` and `tag_id` and `tagger`
- Verify the migration files: 
_- prisma/migrations/20230911154259_drop_tables_tags_questiontags/migration.sql_
_- prisma/migrations/20230911181720_add_table_commenttags/migration.sql_
_-  prisma/migrations/20230911182810_alter_table_comments_adds_tags_fields/migration.sql_
_-  prisma/schema.prisma_
1. Pull the new references to your local environment  and start tracking the branch `backend/tags`
```
git pull 
````   
```
git checkout --track origin/backend/tags
```
2. run the migrations
```
npx prisma migrate dev
```
If you have any issues running the migration, go to the BD …
=> feat: create data schema for comment tags #267 

infrastructure/terraform/main.tf
- Removes Terraform code for deprecated MySQL modules in favor of the new Postgres ones that are used. We couldn't stop the instances without removing these. Just in case these are ever needed, the resources still exist on GCP but "stopped". I ran "terraform state rm cloud_sql.*" for each resource unused so Terraform doesn't track the state of these resources, and we can stop the service in GCP without deleting them forcefully.
=> chore(infra): remove unused mysql cloud sql instances from TF state

app/controllers/comments/tags/create.js, app/controllers/comments/tags/list.js, app/utils/constants.js, app/utils/validators/comments.js, tests/fixtures/tags.json, tests/integration/controllers/comments/tags/createTags.test.js, tests/integration/controllers/comments/tags/listTags.test.js, tests/tearDownDb.js
— add controller to create and get tags `commentstags`
> - app/controllers/comments/tags/create.js
> - app/controllers/comments/tags/list.js
1. Pull the new references to your local environment and start tracking the branch backend/add-list-tags-controller.
```
git pull;
git checkout --track origin/backend/add-list-tags-controller;
```
2. run the tests with the command
```
npm run test:integration
``` 
⚠️ Remember, you have to run the container of your test-database. See the Dockerfile to see the configuration
Closes #278 
(Screenshots of the feature if available.)
=> feat: add controller to create and fetch tags. 

app/components/Atoms/Label/Label.jsx, app/components/Modals/TagsModal/TagModal.jsx, app/components/Modals/TagsModal/TagModal.styled.jsx, app/components/Modals/TagsModal/index.js, app/components/QuestionComment/QuestionComment.jsx, app/components/QuestionComment/QuestionComment.styled.jsx, app/controllers/comments/list.js, app/controllers/comments/tags/list.js, app/root.jsx, app/routes/questions/$questionId.jsx, app/utils/actions.js
- adds the feature to tag a comment, this option is only available for admins. 
1. Pull the new references to your local environment and start tracking the branch frontend/commenttags.
```
git pull;
git checkout --track origin/frontend/commenttags;
```
2 run the project
```
npm run dev
```
3. Insert some data in the table `INSERT INTO wizeq.commenttags (tag_text)  values ('violate guidelines');`
5. Double check that you have admins permissions. 
6. Log in and go to the details of a question with comments 
7. Click to the icon <img width="27" alt="Screen Shot 2023-09-22 at 17 06 42" src="https://github.com/wizeline/wize-q-remix/assets/97203617/5477c910-f5d5-42e8-987c-ea0e4e538abc"> (this is going to show a modal) 
8. You can select a tag, change the existing one or remove it. 
9. :tada: …
=> feat: modal to tag a comment

app/components/CustomDropdown/CustomDropdown.Styled.jsx, app/components/CustomDropdown/CustomDropdown.jsx, app/components/Filters/Filters.jsx, app/controllers/questions/list.js, app/utils/constants.js, tests/integration/controllers/questions/listQuestion.test.js
- add the option to filter the questions depending on the answer that they have. 
- answered:  official answer and comment approved by an admin. 
- not answered: not an official answer and community answer. 
-  Go to the list controller inside question folder. 
- Run test with `npm run test:integration`
1. Pull the new references to your local environment and start tracking the branch fix-filter-status.
```
git pull;
git checkout --track origin/fix-filter-status;
```
2. Run the application. 
```
npm run dev
```
3. In the home page, filter by status and verify that the results are correct.
Closes #283 
https://github.com/wizeline/wize-q-remix/assets/97203617/7617eae5-e9ed-402a-895a-88b1793f7358
=> fix: filter status

app/controllers/embeddings/create.js, app/utils/openai/index.js, tests/unit/utils/openai/embeddings.test.js
- Fixes crash on answer creation caused by openai embeddings implementation.
1. Set your OPENAI_API_KEY in .env to "undefined" (this is temporarily the current value in develop and prod environments)
2. Create an answer for any question and verify the console error is ooutput, but it doesn't crash the app.
=> fix: improve openai embeddings error handling

app/components/QuestionForm/QuestionForm.jsx, app/config/flags.json
introduces a new feature flag named `postAnonymousQuestions` that allows toggling the ability to post questions anonymously. The flag is implemented to control the visibility of the anonymousposting feature, giving flexibility to enable or disable it.
- verify that the `postAnonymousQuestions` is `false`
1. Log in.
2. Navigate to the page to create a new question (click on 'Ask Question').
3. Ensure that you do not see the option to post an anonymous question.
4. Create a question.
5. Open the file `` and modify the value of `postAnonymousQuestions` to true.
6. Repeat step 2.
7. You should now see the option to post anonymous questions.
8. Create a question (both anonymous and non-anonymous).
we want to temporary restrict the option to post anonymous questions. 
Closes #291 
[feature …
=> feat: Add feature flag for enabling/disabling anonymous question posting

app/components/QuestionRow/QuestionRow.jsx
- add condition only admins can see the option to publish a question
1. login as normal user (not admin) 
2. create anonymous question 
3. Verify that you cannot see the option to publish a question
4. :tada:
=> fix: only admin can publish an anonymous question. 

app/components/Modals/AlertAnonQuestions/AlertAnonQuestions.jsx, app/components/Modals/AlertAnonQuestions/AlertAnonQuestions.styled.jsx, app/components/Modals/AlertAnonQuestions/index.js, app/components/Modals/ValuesMessageModal/ValuesMessageModal.jsx, app/components/Notifications/Notifications.jsx, app/components/QuestionDetail/QuestionDetail.jsx, app/components/QuestionForm/QuestionForm.jsx, app/components/SubmitWithModal/SubmitWithModal.jsx, app/controllers/questions/create.js, app/routes/questions/$questionId.jsx, app/routes/questions/new.jsx, app/utils/constants.js
- Show a modal to inform the users, that they have to copy the link, after they created an anonymous question.
1. Login
2. Create an anonymous question
3. Verify that you can see the new modal and that you can copy the link using the button for that action
4. Create a question as normal user and verify that you can see the normal toast alert. 
5. :tada:
This change was a requirement after the session that we have with the stakeholder. 
Closes #x
https://github.com/wizeline/wize-q-remix/assets/97203617/5d4d30e6-321e-496c-810b-2c37966d0f28
=> feat: Change toast notification to a popup when user creates anonymous question

app/controllers/answers/create.js, app/utils/slack/slackNotifications.js, tests/integration/controllers/answers/createAnswer.test.js
-change the configuration to post the answer for anon question when is public
1. Pull this branch 
2. Run the project
3. Add the next environment variables `SLACK_WEBHOOK_URL`, `SLACK_WEBHOOK_URL_ADMIN` and `SLACK_WIZEQ_DOMAIN` if you don't have the values, send me a DM. 
4. Login as admin
5. Post anonymous question (you have to see one post in the slack channel #wize-q-dev)
6. Answer the anon question (you have to see one post in the slack channel #wize-q-dev)
7. Post normal question (you have to see 2 posts in the slack channel #wize-q-dev)
8. Answer normal question (you have to see 2 posts in the slack channel #wize-q-dev)
9. Post anonymous question (you have to see one post in the slack channel #wize-q-dev)
10. Publish the question (you have to see one post in the slack channel …
=> fix: post the answer for anon question when is public. 

.gitignore, app/components/QuestionComment/QuestionComment.jsx
(A brief explanation synthesizing the feature, bug or fix.)
the LF character in the comments (char 10) is replaced with a breakline in react-markdown rendering
.replace(String.fromCharCode(10), '\n\n')
The double \n\n is needed in this library to render a  new ```<p>``` for each line.
=> fix: issue 301 New lines are ignored in comments

infrastructure/terraform/iam.tf, infrastructure/terraform/service-accounts.tf
- Add new Service Account for WizePrompt Team
- Grant that SA permissions to read all CloudSQL instances in WizeQ project
Changes in Terraform File
Terraform Plan (TBD, configuring local env)
WizePrompt team reached out to me about the SA
None on WizeQ side
=> feat(infra): Add SA for WizePrompt team with read permissions on CloudSQL instances

app/components/ListQuestions/ListQuestions.Styled.jsx
Currently the main container grows width to cover the content, no matters if the screen is not capable to contain it
you can run the project locally and test several mobile versions
=> fix: set width of wrapper to 100%
