wizeline/wize-q-remix

.github/workflows/lint .yaml
.github/workflows/test.yaml

- Attempts to add linting and testing to github action workflow

chore(tests): add github actions

---

app/controllers/comments/list.js
app/utils/backend/comments.js
app/utils/backend/validators/comments.js
prisma/migrations/20221017192245_add_comment_user_fk/migration.sql
prisma/migrations/20221018005451_add_comment_approver_fk/migration.sql
prisma/schema.prisma
tests/fixtures/commentVotes.json
tests/fixtures/comments.json
tests/fixtures/users.json
tests/integration/controllers/comments/listComments.test.js
tests/setup.js

- Add the comments list controller. 
- controllers/comments/list
- test/comments/listComments.test.js
1. Run the migrations `npx prisma migrate dev`. 
To make sure that you add the two foreign keys to the Comment's table (`user`, `approver`)
2. Verify that you add the foreign keys to your schema. Run  `npx  prisma db pull` to update your schema according to the database.
3. Run the test with the next command `npm run test:integration`
4. Verify that all test passed. 
If you have any issues running the migrations, you can delete the information of the table of the prisma migrations (`_prisma_migrations`), then mark as applied the initial migration running the next command `npx prisma migrate resolve --applied 20220925023006_initial_migration` and then run all the migration with: `npx …

feat(migration): add comments list controller

---

app/controllers/comments/update.js
app/utils/backend/validators/comments.js
app/utils/constants.js
tests/fixtures/comments.json
tests/integration/controllers/comments/updateComment.test.js

It adds the update comment controller and the integration tests to validate it
- app/controllers/comments/update.js
- tests/integration/controllers/comments/updateComment.test.js
Validated by the integration tests
Closes #42

feat(migration): Add update comment controller with integration tests

---

app/routes/about.jsx
app/styles/About.Styled.jsx

- updates repo link
- update bullet points style (Things to Keep in Mind When Asking a Question)
- In app/routes/about.jsx
1. Make sure the new link on the About page redirects you to the wize-q-remix repo
2. Check the blue bullet pts are displayed correctly
3. 🎉 
Closes #52

feat: update about/contact page 

---

app/components/AppNavbar/AppNavbar.Styled.jsx
app/components/AppNavbar/AppNavbar.jsx
app/styles/global.css
app/styles/sass/App.scss

- Updates navbar style
- app/components/AppNavbar
1. Make sure that the component behaves normally and looks correctly in desktop and mobile version
2. 🎉 
Closes #57

feat: update navbar style

---

app/components/Modals/AssignAnswerModal/AssignAnswerModal.Styled.jsx
app/components/Modals/AssignAnswerModal/AssignAnswerModal.jsx
app/components/QuestionDetail/QuestionDetail.jsx
app/routes/questions/$questionId.jsx
app/utils/actions.js

Migrates Question detail Page to wize q remix
implements the assign department feature with its controller
components/Modals/AssignAnswerModal/AssignAnswerModal.jsx
routes/questions/$questionId.jsx
1. Log in as an admin to wizeline questions
2. click on any question to enter de question detail modal
3. click on re assign question and select any department, the question should be re assigned to the selected department
Closes #37

feat: Migrate Question Detail Page - Re-assign department 

---

app/routes/questions/$questionId.jsx

- Redirects to 404 page when question is undefined meaning that the question was not found
1. Go to a question detail page of a non existing question (e.g. http://localhost:3000/questions/999999999999999)
2. Verify redirected 404 page and not error
Closes #85

fix: redirect question detail page to 404 on invalid id

---

app/components/AnswerRow/AnswerRow.jsx
app/components/Atoms/Label/Label.Styled.jsx
app/components/Atoms/Label/Label.jsx
app/components/QuestionCard/QuestionCard.jsx
app/components/QuestionComment/QuestionComment.jsx
app/controllers/questions/list.js
app/utils/backend/constants.js
app/utils/questionUtils.js

(A brief explanation synthesizing the feature, bug or fix.)
-  Show the different type of answer for a question.
> If there is an official answer, show it on the homepage, if not, search for a comment approved by the admin, if it exists, show it on the homepage and if it is the last one not exists, search for a comment marked as a community response, if it exists, show it on the homepage.
> If none of the above options exist, it should not show anything.
1. Login
2. If a question has an answer, verify that you can see in the homepage
3. If a question has an approved comment as an answer and no official answer, the comment should show as an answer labeled "Comment Approved By ......" instead of "Best Answer".
4. If a question has a comment marked as a community answer and does not have an …

feat: (frontend) Sort-Show answers in HomePage.

---

app/controllers/profile/questionsCreated.js
app/utils/backend/validators/profile.js
tests/integration/controllers/profile/questionsCreated.test.js

- Added controller to get lists of questions created by user
- app/controllers/profile/questionsCreated.js
- Make sure that all tests related to this controller pass correctly.
Closes #97

feat(migration): add get questions created by user controller with integration tests

---

app/components/ListQuestions/ListQuestions.jsx
app/components/Login/LoginContainer.jsx
app/components/Modals/ValuesMessageModal/ValuesMessageModal.Styled.jsx
app/components/Modals/ValuesMessageModal/ValuesMessageModal.jsx
app/utils/cookies.js

- Add an alert to show the message with the values of Wizeline, When the user log in. 
-  app/components/ListQuestions/ListQuestions.jsx 
-  app/components/Login/LoginContainer.jsx
-  app/components/Modals/ValuesMessageModal/ValuesMessageModal.Styled.jsx
-  app/components/Modals/ValuesMessageModal/ValuesMessageModal.jsx
-  app/utils/cookies.js
1. Login
2. Verify that the message appears, then close it.
3. Go to another page and go to the home page and verify the message not appears. 
4. Logout 
5. Login and verify that the message appears again.
Closes #128
https://user-images.githubusercontent.com/97203617/207971638-b5b0c3d1-0521-49cb-bbc1-863228211d58.mov

chore: Add message with the values of Wizeline

---

app/components/QuestionForm/QuestionForm.jsx
app/controllers/employees/list.js

This pull request will fix two issues, one if there is duplicated records on the employees department table will only get uniques, and now will properly assign the question to a person 
Login
Click on the Ask question button
Select a department
Verify that the people dropdown is displayed
If there is people displayed, select a person displayed
Verify that you can create the question

fix: added unique filter and fixed param assignation

---

app/components/QuestionForm/QuestionForm.jsx
app/controllers/employees/list.js
app/routes/questions/new.jsx

- Add the _I don't know whom to assign it_ option to the department list when create a question. 
- app/controllers/employees/list.js
- app/routes/questions/new.jsx
1. Login.
2. Go to create a new question.
3. Display the department list and verify that you can see the option  '_I don't know whom to assign it_'
4. Select the option '_I don't know whom to assign it_' and finish the creation of a question. 
5. In the HomePage select the option _'No Assigned'_ of department filter and verify that you can see the question that you created. 
6. :tada:
Closes #155

chore: Add  _I don't know whom to assign it_ option to department list. 

---

app/controllers/profile/questionsAnswered.js
app/controllers/profile/questionsCreated.js
app/utils/backend/validators/profile.js
tests/integration/controllers/profile/questionsAnswered.test.js

- Adds new controller to get questions answered by a specific user, which will be used in profile view in the future.
- Go to the new controller file
1. Tested by integration tests, not implemented in frontend yet.
- I know this is not the project's priority right now, but had this already developed last week so I might as well push it.
Closes #160

feat: add questions answered by user controller for profile

---

app/controllers/questions/list.js
prisma/schema.prisma

- This one liner allows the homepage to filter all questions to non-admin users that aren't public nor enabled. 
app/controllers/questions/list.js
- The front-end part of to make a question private is not available at the moment*
Closes #166

feat: Added public filter to question list

---

infrastructure/terraform/main.tf

- Quick fix for Terraform misconfiguration from previous PR. Tested locally with Terraform plan.

fix: use email secret values for terraform correctly

---

app/components/QuestionRow/QuestionRow.jsx
app/controllers/questions/publishQuestion.js
app/routes/index.jsx
app/routes/questions/$questionId.jsx
app/utils/actions.js
app/utils/constants.js
tests/integration/controllers/questions/publishQuestion.test.js

- add the controllers to manage the new functionality to publish an anonymous question in the home page. 
- add the option in the QuestionRow Component to publish an anoymous question in the home page (this option is only available to admins) 
- run the test (`npm run test:integration`)
- run the project and see the option in the home page (only if the user is admin) 
> ### BEFORE START: 
> - Update the anonymous question in your database running 
> ```
> SET SQL_SAFE_UPDATES = 0;
> UPDATE wizeq.Questions 
> SET is_public = false 
> WHERE is_anonymous = true;
> SET SQL_SAFE_UPDATES = 1;
> ```
> and verify that all the anonymous questions `is_public = false ` 
> `SELECT * FROM wizeq.Questions WHERE is_anonymous = true;
> `
1. Login as normal user. (without admin permissions)
2. Verify that …

feat: Publish an anonymous question. 

---

app/components/CommentInput/CommentInput.jsx
app/components/CommentInput/CommentInputAuthor.jsx
app/components/QuestionDetail/QuestionDetail.jsx

This feature will prevent anonymous users to comment on unpublished questions. 
app/components/CommentInput/CommentInput.jsx
app/components/CommentInput/CommentInputAuthor.jsx
app/components/QuestionDetail/QuestionDetail.jsx
Closes #165
In the development database I don't have the assets for my profile picture or the anonymous picture**
Published question 
Unpublished question

feat: Removed the option to create anonymous comment on unpublished questions

---

app/components/Atoms/Label/Label.Styled.jsx
app/components/QuestionDetailInfo/QuestionDetailInfo.jsx
app/components/QuestionRow/QuestionRow.jsx
app/controllers/questions/getQuestionById.js
app/controllers/questions/list.js
app/routes/questions/$questionId.jsx
app/styles/global.css

- Adds nullable "assigned employee" tag to question card in both list and detail page.
- To achieve this, the listQuestions and questionById controller now return the name of the assigned employee.
Have two questions with both an assigned employee and one without one.
1. Verify that the question with the assigned employee dislpays the full name in both list and detail page
2. Verify that the question without an assigned employee works as before.
Closes #182

feat: add assigned employee label on question card if applies

---

app/components/Filters/Filters.jsx
app/controllers/questions/list.js
app/routes/index.jsx
app/utils/constants.js

- Add filter enabled questions
- Fix default department selected option
Use a admin user to validate the question list
1. Login with a Admin account
2. Check that the Enabled filter is available
3. Select the options in the Enabled
4. Validate the list
Closes #193

feat: Add filter enabled questions

---

app/components/Modals/AssignAnswerModal/AssignAnswerModal.jsx
app/controllers/questions/assignQuestion.js
app/routes/questions/$questionId.jsx
app/utils/backend/validators/question.js
tests/integration/controllers/questions/assignQuestion.test.js

- adds functionality to reassign a question to and employee by department
1. Login as an admin
2. Go to the question detail 
3. Reassign a question to another department and person
4. Verify that the data of the assignation change to the new ones.
Closes #192 
https://user-images.githubusercontent.com/97203617/234736629-7fe49dc9-9c6e-4a9c-a24d-a9f1546f135b.mov

feat: reassign an employee

---

infrastructure/terraform/main.tf

- fix terraform validation by adding .secret_data in main.tf

fix: terraform validation

---

app/config/flags.json
app/controllers/emails/getPendingEmailsForDeparments.js
app/controllers/emails/getPendingQuestionsByEmployeed.js
app/controllers/emails/getPendingQuestionsForDepartment.js
app/controllers/emails/sendEmployeesReminder.js
app/controllers/emails/sendManagerReminder.js
app/routes/api/emails/sendEmployeesReminder.jsx
app/routes/api/emails/sendManagerReminder.jsx
app/utils/backend/emails/emailConstants.js
app/utils/backend/emails/templates/views/questionPendingReminderByEmployee.hbs
app/utils/timeOperations.js
infrastructure/terraform/main.tf
tests/integration/controllers/emails/getPendingEmailsForDepartment.test.js
tests/integration/controllers/emails/getPendingQuestionsForDepartment.test.js
tests/integration/controllers/emails/sendReminder.test.js

- adds controller to send the emails reminder to employees.
- adds template for the new email
- saves the date of the last email notification in the table of Questions.

feat: email employee reminder

---

app/controllers/emails/sendEmployeesReminder.js

- adds the conditional to return null when the question list is empty
- adds the condition of not sending the email if the value is empty.

fix: empty list question on emails

---

app/components/Modals/ValuesMessageModal/ValuesMessageModal.jsx

- Edith the values messages, change manager to TPLs. 
`app/components/Modals/ValuesMessageModal/ValuesMessageModal.jsx`
1. Log out and Log in 
2. Verify the change in the first messages that appears. 
3. :tada:

fix: Values Message, change manager to TPLs

---

app/utils/constants.js

-removes the unused constant ROUTES 
- app/utils/constants.js
Closes #227

fix: using insecure http protocol

---

.eslintrc
package-lock.json
package.json

- Removes unused dependencies. Used this library https://www.npmjs.com/package/depcheck to check which dependencies are not used anymore.
- Adds remix recommended eslint rules
- Verify app is working as usual.
Closes #234

chore(deps): remove unused dependencies

---

app/routes/questions/$questionId.jsx

Fix a navigation issue when entering the app with a link 
app/routes/questions/$questionId.jsx
Access any question link directly with the link without any previous navigation
none
Closes #254
:camera:
:question:

fix: fixed routing redirection

---

.env.test.integration
.github/workflows/test.yaml
tests/fixtures/answers.json
tests/fixtures/commentVotes.json
tests/fixtures/comments.json
tests/fixtures/departments.json
tests/fixtures/nps.json
tests/fixtures/questions.json
tests/fixtures/users.json
tests/fixtures/votes.json
tests/tearDownDb.js

(A brief explanation synthesizing the feature, bug or fix.)
- this
- that
(Explain where the reviewer should start in order to review the whole addition or subtractions.)
:checkered_flag:
1. :one:
2. :two:
3. :tada:
(Any information regarding the PR that the reviewer should know.)
:construction:
Closes #x
(Screenshots of the feature if available.)
:camera:
(If available, to another developer or reviewer.)
:question:

chore(CI): github actions postgres

---

.gitignore
app/components/AnswerRow/AnswerRow.jsx
app/components/Modals/AnswerModal/AnswerModal.jsx
app/components/Modals/DeleteAnswerModal/DeleteAnswerModal.jsx
app/components/QuestionCard/QuestionCard.jsx
app/components/QuestionComment/QuestionComment.jsx
app/components/QuestionDetail/QuestionDetail.jsx
app/utils/comments/commentUtils.js
app/utils/comments/comments.js

-Fix the name of the props that were with a Capital letter.
1. Double check that you have admin permissions. 
2. Use the option to approve a comment
3. :tada:
Closes: https://github.com/wizeline/wize-q-remix/issues/263
:camera:
⚠️  Remember that you should have your local environment with Postgres.
I'm working in the documentation, but for now you can follow the instruction of this PR: https://github.com/wizeline/wize-q-remix/pull/258

fix: props names

---

app/controllers/comments/tags/tagging.js
app/utils/validators/comments.js
tests/fixtures/comments.json
tests/fixtures/tags.json
tests/initTestDb.js
tests/integration/controllers/comments/tags/taggingComment.test.js

- add the controller to handle the manipulation of the tag in the comments
- add the unit test for the controller to tag a comment.
1.  Pull the new references to your local environment and start tracking the branch `backend/tags-controller`
```
git pull;
git checkout --track origin/backend/tags-controller;
```
2. run the tests with the command
```
npm run test:integration
```
⚠️  Remember, you have to run the container of your test-database. See the Dockerfile to see the configuration
3. :tada:
Closes #268 
(Screenshots of the feature if available.)
:camera:

feat: Controller - Tagging a comment.

---

app/components/QuestionComment/QuestionComment.jsx
app/components/QuestionComment/QuestionComment.styled.jsx
app/components/QuestionCommentList/QuestionCommentList.jsx
app/config/flags.json
app/controllers/questions/list.js
app/routes/admin.jsx

- add the configuration to add the feature of tagging comments as feature flag. 
- add a blur filter when comment has a tag
- change color of the tag.
1. Log in with admin permissions.
2. Navigate to the admin menu and verify that you can see the 'Tags' tab.
3. Select a question with comments and tag one of them. (If you don't have any tags, you need to add some first.)
4. The comment should change, displaying blurred text and a button on the left side.
5. Go to `app/config/flags.json` and change `taggingComments` to `false`.
6. Return to the admin page and confirm that you cannot see the 'Tags' tab.
7. Revisit the previously tagged comment and confirm that it appears as a normal comment without the tag 
Closes #266 
[feature flag: true]
- …

feat: Tagging comments as feature flag

---

app/components/QuestionRow/QuestionRow.jsx
app/config/flags.json
app/controllers/answers/create.js
app/controllers/questions/create.js
app/controllers/questions/list.js
app/controllers/questions/publishQuestion.js
app/routes/index.jsx
app/routes/questions/$questionId.jsx
app/utils/actions.js
app/utils/constants.js
app/utils/slack/slackNotifications.js
mydb.sql
prisma/migrations/20231218194545_add_is_public_column/migration.sql
prisma/schema.prisma
tests/fixtures/questions.json
tests/integration/controllers/answers/createAnswer.test.js
tests/integration/controllers/questions/assignQuestion.test.js
tests/integration/controllers/questions/createQuestion.test.js
tests/integration/controllers/questions/listQuestion.test.js
tests/integration/controllers/questions/publishQuestion.test.js

- Adds toggeable private questions for anonymous questions
- Allows admins to publish the question to the public
- Create an anonymous question
- Verify a non-admin user can not see this question in the homepage list. But an admin can.
- Verify the admin can click on the "publish question" with a lock icon, and this makes the question public.

feat: private questions

---

app/components/Notifications/Notifications.jsx
app/controllers/questions/create.js
app/utils/constants.js

- Change the message when the user creates an anonymous questions, inform the user to save the link. 
1. Login 
2. Create an anonymous question.
3. :tada: 
Closes #x

feat: alert with link of anonymous question. 

---

app/routes/about.jsx
app/styles/About.Styled.jsx

- update the content of the about page according to the following modification : https://docs.google.com/document/d/1DoOks0Zgcfz-yme6ZizPMzcdhyo6Gm4iweHQ6OAmO3E/edit?usp=sharing
1.  Pull this branch
2. Run the project 
3. Login 
4. Go to the about page
5. :tada:

feat: update about page

---

app/components/AdminDepartments/AdminDepartments.jsx
app/components/AdminTags/AdminTags.jsx
app/components/AdminUsersTable/AdminUsersTable.jsx
app/components/AnswerRow/AnswerRow.jsx
app/components/Atoms/Button/Button.jsx
app/components/Atoms/Input/Input.jsx
app/components/CounterButton/CounterButton.jsx
app/components/CustomDropdown/CustomDropdown.jsx
app/components/GoToTopButton/GoToTopButton.jsx
app/components/Modals/AddEditTagModal/AddEditTagModal.jsx
app/components/Modals/AssignedUserToDeparmentModal/AssignedUserToDeparmentModal.jsx
app/components/Modals/EditUserModal/EditUserModal.jsx
app/components/SearchDropdown/SearchDropdown.jsx
app/components/SearchDropdown/index.js
app/components/Tab/DefaultTabs.jsx
app/routes/admin.jsx
app/routes/contact.jsx

- Addresses / fixes all (if not most) warnings that were showing up during development.
- Browse the page and use multiple features (dropdowns, filters, etc.). Verify no warnings are shown on the console.
Closes #288

fix: address multiple console warnings

---

infrastructure/terraform/iam.tf
infrastructure/terraform/service-accounts.tf

… on CloudSQL instances (#307)"
This reverts commit b3ad8ee6052f106ea3053cbd8827a210adf9d67e.
(A brief explanation synthesizing the feature, bug or fix.)
- this
- that
(Explain where the reviewer should start in order to review the whole addition or subtractions.)
:checkered_flag:
1. :one:
2. :two:
3. :tada:
(Any information regarding the PR that the reviewer should know.)
:construction:
Closes #x
(Screenshots of the feature if available.)
:camera:
(If available, to another developer or reviewer.)
:question:

fix: revert #307
